# ---------------------------------------------------------------------------
# WARNING: This file was auto-generated by classExposer.generator.
# It is brittle by design—manual edits are likely to be lost on regeneration.
# Update the metadata or manifests instead, then re-run the generator.
# ---------------------------------------------------------------------------
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from interFEBio.common.base import Annotated, FEBioEntity, RangeSpec


class FECoreBase(FEBioEntity):
    pass

class FEParamContainer(FEBioEntity):
    pass

__all__ = [
    'FEAnalysis',
    'FETimeStepController',
]

@dataclass(kw_only=True)
class FEAnalysis(FECoreBase):
    class PlotLevel(Enum):
        PLOT_NEVER = 0
        PLOT_MAJOR_ITRS = 1
        PLOT_MINOR_ITRS = 2
        PLOT_MUST_POINTS = 3
        PLOT_FINAL = 4
        PLOT_AUGMENTATIONS = 5
        PLOT_STEP_FINAL = 6

    class OutputLevel(Enum):
        OUTPUT_NEVER = 0
        OUTPUT_MAJOR_ITRS = 1
        OUTPUT_MINOR_ITRS = 2
        OUTPUT_MUST_POINTS = 3
        OUTPUT_FINAL = 4

    analysis: int = field(default=0, metadata={'fe_name': 'analysis', 'default': 0})
    time_steps: Annotated[int, 'RangeSpec(min=-1, min_inclusive=True)'] = field(default=10, metadata={'fe_name': 'time_steps', 'range': {'min': -1, 'min_inclusive': True}, 'default': 10})
    step_size: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0.1, metadata={'fe_name': 'step_size', 'units': 'UNIT_TIME', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0.1})
    plot_zero_state: bool = field(default=False, metadata={'fe_name': 'plot_zero_state', 'default': False})
    plot_range: tuple[int, int] = field(default=(0, -1), metadata={'fe_name': 'plot_range', 'default': '0, -1'})
    plot_level: PlotLevel | int = field(default=PlotLevel.PLOT_MAJOR_ITRS, metadata={'fe_name': 'plot_level', 'enum': ['PLOT_NEVER', 'PLOT_MAJOR_ITRS', 'PLOT_MINOR_ITRS', 'PLOT_MUST_POINTS', 'PLOT_FINAL', 'PLOT_AUGMENTATIONS', 'PLOT_STEP_FINAL'], 'enum_class': 'PlotLevel', 'default': 1})
    output_level: OutputLevel | int = field(default=OutputLevel.OUTPUT_MAJOR_ITRS, metadata={'fe_name': 'output_level', 'enum': ['OUTPUT_NEVER', 'OUTPUT_MAJOR_ITRS', 'OUTPUT_MINOR_ITRS', 'OUTPUT_MUST_POINTS', 'OUTPUT_FINAL'], 'enum_class': 'OutputLevel', 'default': 1})
    plot_stride: int = field(default=1, metadata={'fe_name': 'plot_stride', 'default': 1})
    output_stride: int = field(default=1, metadata={'fe_name': 'output_stride', 'default': 1})
    adaptor_re_solve: bool = field(default=True, metadata={'fe_name': 'adaptor_re_solve', 'long_name': 're-solve after adaptation', 'default': True})
    time_stepper: Optional[FETimeStepController] = field(default=None, metadata={'fe_name': 'time_stepper', 'is_property': True, 'optional': True})
    fe_class: str = field(init=False, default='analysis')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FETimeStepController(FEParamContainer):
    max_retries: int = field(default=5, metadata={'fe_name': 'max_retries', 'long_name': 'max retries', 'default': 5})
    opt_iter: int = field(default=11, metadata={'fe_name': 'opt_iter', 'long_name': 'optimal iterations', 'default': 11})
    dtmin: float = field(default=0, metadata={'fe_name': 'dtmin', 'long_name': 'min stepsize', 'default': 0})
    dtmax: float = field(default=0.1, metadata={'fe_name': 'dtmax', 'long_name': 'max stepsize', 'default': 0.1})
    aggressiveness: int = field(default=0, metadata={'fe_name': 'aggressiveness', 'default': 0})
    cutback: float = field(default=0.5, metadata={'fe_name': 'cutback', 'default': 0.5})
    dtforce: bool = field(default=False, metadata={'fe_name': 'dtforce', 'default': False})
    fe_class: str = field(init=False, default='default')
    xml_tag: str = field(init=False, default='')
