# Auto-generated by codegen.generator
from __future__ import annotations

from dataclasses import dataclass, field, fields
from typing import Any, Optional
import xml.etree.ElementTree as ET

def _indent(element: ET.Element, level: int = 0) -> None:
    '''Recursively indent an XML tree for pretty-printing.'''

    children = list(element)
    if children:
        if not element.text or not element.text.strip():
            element.text = '\n' + '  ' * (level + 1)
        for child in children:
            _indent(child, level + 1)
            if not child.tail or not child.tail.strip():
                child.tail = '\n' + '  ' * (level + 1)
        if not children[-1].tail or not children[-1].tail.strip():
            children[-1].tail = '\n' + '  ' * level
    elif level and (not element.tail or not element.tail.strip()):
        element.tail = '\n' + '  ' * level

class FEBioEntity:
    '''Base class for generated FEBio bindings.

    Attributes:
        fe_class: Name of the FEBio class represented by the binding.
        xml_tag: XML tag used for serialisation.
        xml_section: FEBio section that hosts the entity.
    '''

    fe_class: str = ''
    xml_tag: str = ''
    xml_section: str = ''

    def to_xml_element(self, name: str | None = None, *, tag_override: str | None = None) -> ET.Element:
        '''Serialise the entity into an XML element.

        Args:
            name: Optional name attribute for the FEBio element.

        Returns:
            Constructed XML element.
        '''

        tag = tag_override or self.xml_tag or 'bc'
        element = ET.Element(tag)
        element.set('type', self.fe_class)
        if name:
            element.set('name', name)
        for field_info in fields(self):
            if field_info.name in {'fe_class', 'xml_tag', 'xml_section'}:
                continue
            value = getattr(self, field_info.name)
            if value is None:
                continue
            metadata = field_info.metadata or {}
            param_name = metadata.get('fe_name', field_info.name)
            if metadata.get('is_property'):
                self._append_property_element(element, param_name, value)
                continue
            # Parameters are written as direct child tags instead of <param name="...">.
            param_element = ET.SubElement(element, param_name)
            param_element.text = str(value)
        return element

    def _append_property_element(self, parent: ET.Element, tag: str, value: Any) -> None:
        '''Append a property element handling FEBioEntity nesting.'''

        if isinstance(value, FEBioEntity):
            child = value.to_xml_element(tag_override=tag)
            parent.append(child)
            return
        if isinstance(value, (list, tuple)):
            for item in value:
                if item is None:
                    continue
                self._append_property_element(parent, tag, item)
            return
        prop_element = ET.SubElement(parent, tag)
        prop_element.text = str(value)

    def to_xml_string(self, name: str | None = None) -> str:
        '''Return the XML representation as a string.

        Args:
            name: Optional name attribute for the FEBio element.

        Returns:
            XML string representing the entity.
        '''

        element = self.to_xml_element(name=name)
        _indent(element)
        return ET.tostring(element, encoding='unicode')

from ..Core import FEConstValueMat3d
from ..Core import FEMappedValueMat3d
from ..Core import FEMat3dCylindricalMap
from ..Core import FEMat3dLocalElementMap
from ..Core import FEMat3dPolarMap
from ..Core import FEMat3dSphericalMap
from ..Core import FEMat3dVectorMap

@dataclass
class Vec3d:
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0

    def __str__(self) -> str:
        return f"{self.x}, {self.y}, {self.z}"

class FEBodyForce(FEBioEntity):
    pass

class FEBoundaryCondition(FEBioEntity):
    pass

class FECoreClass(FEBioEntity):
    pass

class FEDamageCDF(FEBioEntity):
    pass

class FEDamageCDFGamma(FEBioEntity):
    pass

class FEDamageCDFLogNormal(FEBioEntity):
    pass

class FEDamageCDFPQP(FEBioEntity):
    pass

class FEDamageCDFStep(FEBioEntity):
    pass

class FEDamageCDFUser(FEBioEntity):
    pass

class FEDamageCDFWeibull(FEBioEntity):
    pass

class FEDamageCriterion(FEBioEntity):
    pass

class FEElasticMaterial(FEBioEntity):
    pass

class FEFixedBC(FEBioEntity):
    pass

class FEMat3dValuator(FEBioEntity):
    pass

class FEMat3dsValuator(FEBioEntity):
    pass

class FENodalBC(FEBioEntity):
    pass

class FENodalLoad(FEBioEntity):
    pass

class FEParamMat3d(FEBioEntity):
    pass

class FEParamVec3(FEBioEntity):
    pass

class FEPrescribedNodeSet(FEBioEntity):
    pass

class FEPrescribedSurface(FEBioEntity):
    pass

class FEPrestrainGradient(FEBioEntity):
    pass

class FESurfaceLoad(FEBioEntity):
    pass

class FEUncoupledMaterial(FEBioEntity):
    pass

class mat3d(FEBioEntity):
    pass

class mat3ds(FEBioEntity):
    pass

class tens3drs(FEBioEntity):
    pass

__all__ = [
    'FEConstPrestrainGradient',
    'FEDamageCDFSimo',
    'FEDamageCriterionDrucker',
    'FEDamageMaterialUC',
    'FEFungOrthotropic',
    'FEIncompNeoHookean',
    'FEIsotropicElastic',
    'FEPreStrainUncoupledElastic',
    'FEPrestrainElastic',
    'FEYeoh',
]

@dataclass
class FEConstPrestrainGradient(FEPrestrainGradient):
    ramp: Optional[float] = field(default=None, metadata={'fe_name': 'ramp'})
    f0: Optional[FEParamMat3d] = field(default=None, metadata={'fe_name': 'F0'})
    fe_class: str = field(init=False, default='prestrain gradient')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEDamageCDFSimo(FEDamageCDF):
    a: Optional[float] = field(default=None, metadata={'fe_name': 'a', 'range': {'min': 0.0, 'min_inclusive': False}})
    b: Optional[float] = field(default=None, metadata={'fe_name': 'b', 'range': {'min': 0.0, 'max': 1.0, 'min_inclusive': True, 'max_inclusive': True}})
    fe_class: str = field(init=False, default='CDF Simo')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEDamageCriterionDrucker(FEDamageCriterion):
    c: Optional[float] = field(default=None, metadata={'fe_name': 'c', 'range': {'min': '-27.0/8.0', 'max': '9.0/4.0', 'min_inclusive': True, 'max_inclusive': True}})
    fe_class: str = field(init=False, default='DC Drucker shear stress')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEDamageMaterialUC(FEUncoupledMaterial):
    elastic: Optional[FEUncoupledMaterial] = field(default=None, metadata={'fe_name': 'elastic', 'is_property': True})
    damage: Optional[FEDamageCDF | FEDamageCDFSimo | FEDamageCDFLogNormal | FEDamageCDFWeibull | FEDamageCDFStep | FEDamageCDFPQP | FEDamageCDFGamma | FEDamageCDFUser] = field(default=None, metadata={'fe_name': 'damage', 'is_property': True})
    criterion: Optional[FEDamageCriterionDrucker] = field(default=None, metadata={'fe_name': 'criterion', 'is_property': True})
    fe_class: str = field(init=False, default='uncoupled elastic damage')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEFungOrthotropic(FEUncoupledMaterial):
    e1: Optional[float] = field(default=None, metadata={'fe_name': 'E1', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': False}})
    e2: Optional[float] = field(default=None, metadata={'fe_name': 'E2', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': False}})
    e3: Optional[float] = field(default=None, metadata={'fe_name': 'E3', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': False}})
    g12: Optional[float] = field(default=None, metadata={'fe_name': 'G12', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': True}})
    g23: Optional[float] = field(default=None, metadata={'fe_name': 'G23', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': True}})
    g31: Optional[float] = field(default=None, metadata={'fe_name': 'G31', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': True}})
    v12: Optional[float] = field(default=None, metadata={'fe_name': 'v12'})
    v23: Optional[float] = field(default=None, metadata={'fe_name': 'v23'})
    v31: Optional[float] = field(default=None, metadata={'fe_name': 'v31'})
    c: Optional[float] = field(default=None, metadata={'fe_name': 'c', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': False}})
    mat_axis: Optional[FEConstValueMat3d | FEMat3dLocalElementMap | FEMat3dSphericalMap | FEMat3dCylindricalMap | FEMat3dPolarMap | FEMat3dVectorMap | FEMappedValueMat3d] = field(default=None, metadata={'fe_name': 'mat_axis', 'is_property': True})
    fe_class: str = field(init=False, default='Fung orthotropic')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEIncompNeoHookean(FEUncoupledMaterial):
    g: Optional[float] = field(default=None, metadata={'fe_name': 'G', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': False}, 'long_name': 'shear modulus'})
    fe_class: str = field(init=False, default='incomp neo-Hookean')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEIsotropicElastic(FEElasticMaterial):
    e: Optional[int] = field(default=None, metadata={'fe_name': 'E', 'units': 'UNIT_PRESSURE', 'range': {'min': 0.0, 'min_inclusive': False}, 'long_name': "Young's modulus"})
    v: Optional[int] = field(default=None, metadata={'fe_name': 'v', 'range': {'min': -1.0, 'max': 0.5, 'min_inclusive': True, 'max_inclusive': False}, 'long_name': "Poisson's ratio"})
    fe_class: str = field(init=False, default='FEIsotropicElastic')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEPreStrainUncoupledElastic(FEUncoupledMaterial):
    elastic: Optional[FEUncoupledMaterial] = field(default=None, metadata={'fe_name': 'elastic', 'is_property': True})
    prestrain: Optional[FEPrestrainGradient] = field(default=None, metadata={'fe_name': 'prestrain', 'is_property': True})
    fe_class: str = field(init=False, default='uncoupled prestrain elastic')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEPrestrainElastic(FEElasticMaterial):
    elastic: Optional[FEElasticMaterial] = field(default=None, metadata={'fe_name': 'elastic', 'is_property': True})
    prestrain: Optional[FEPrestrainGradient] = field(default=None, metadata={'fe_name': 'prestrain', 'is_property': True})
    fe_class: str = field(init=False, default='prestrain elastic')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')

@dataclass
class FEYeoh(FEUncoupledMaterial):
    c1: Optional[Any] = field(default=None, metadata={'fe_name': 'c1', 'units': 'UNIT_PRESSURE'})
    c2: Optional[Any] = field(default=None, metadata={'fe_name': 'c2', 'units': 'UNIT_PRESSURE'})
    c3: Optional[Any] = field(default=None, metadata={'fe_name': 'c3', 'units': 'UNIT_PRESSURE'})
    c4: Optional[Any] = field(default=None, metadata={'fe_name': 'c4', 'units': 'UNIT_PRESSURE'})
    c5: Optional[Any] = field(default=None, metadata={'fe_name': 'c5', 'units': 'UNIT_PRESSURE'})
    c6: Optional[Any] = field(default=None, metadata={'fe_name': 'c6', 'units': 'UNIT_PRESSURE'})
    fe_class: str = field(init=False, default='Yeoh')
    xml_tag: str = field(init=False, default='material')
    xml_section: str = field(init=False, default='Materials')
