# Auto-generated by codegen.generator
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from ..common.base import Annotated, FEBioEntity, RangeSpec

from .parameters import (
    FEParamDouble,
    FEParamVec3,
    FEParamMat3d,
    FEParamMat3ds,
    MeshMappedValue,
)
from . import parameters
from .value_types import Vec3d, mat3d, mat3ds

from ..Core import Vec3d, mat3d, mat3ds

class FEFunction1D(FEBioEntity):
    pass

class FEMat3dValuator(FEBioEntity):
    pass

class FEMat3dsValuator(FEBioEntity):
    pass

__all__ = [
    'FEConstFunction',
    'FEConstValueMat3d',
    'FEConstValueMat3ds',
    'FELinearFunction',
    'FEMappedValueMat3d',
    'FEMappedValueMat3ds',
    'FEMat3dCylindricalMap',
    'FEMat3dLocalElementMap',
    'FEMat3dPolarMap',
    'FEMat3dSphericalAngleMap',
    'FEMat3dSphericalMap',
    'FEMat3dVectorMap',
    'FEMathFunction',
    'FEStepFunction',
    'Vec3d',
    'mat3d',
    'mat3ds',
    'MeshMappedValue',
    'FEParamDouble',
    'FEParamVec3',
    'FEParamMat3d',
    'FEParamMat3ds',
    'parameters',
]

@dataclass(kw_only=True)
class FEConstFunction(FEFunction1D):
    value: float = field(metadata={'fe_name': 'value'})
    fe_class: str = field(init=False, default='const')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEConstValueMat3d(FEMat3dValuator):
    const: mat3d = field(metadata={'fe_name': 'const'})
    fe_class: str = field(init=False, default='const')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEConstValueMat3ds(FEMat3dsValuator):
    const: mat3ds = field(metadata={'fe_name': 'const'})
    fe_class: str = field(init=False, default='const')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FELinearFunction(FEFunction1D):
    slope: float = field(metadata={'fe_name': 'slope'})
    intercept: float = field(metadata={'fe_name': 'intercept'})
    fe_class: str = field(init=False, default='linear ramp')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMappedValueMat3d(FEMat3dValuator):
    map: str = field(metadata={'fe_name': 'map'})
    fe_class: str = field(init=False, default='map')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMappedValueMat3ds(FEMat3dsValuator):
    map: str = field(metadata={'fe_name': 'map'})
    fe_class: str = field(init=False, default='map')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMat3dCylindricalMap(FEMat3dValuator):
    center: Vec3d = field(metadata={'fe_name': 'center'})
    axis: Vec3d = field(metadata={'fe_name': 'axis'})
    vector: Vec3d = field(metadata={'fe_name': 'vector'})
    fe_class: str = field(init=False, default='cylindrical')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMat3dLocalElementMap(FEMat3dValuator):
    local: int = field(metadata={'fe_name': 'local'})
    fe_class: str = field(init=False, default='local')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMat3dPolarMap(FEMat3dValuator):
    center: Vec3d = field(metadata={'fe_name': 'center'})
    axis: Vec3d = field(metadata={'fe_name': 'axis'})
    vector1: Vec3d = field(metadata={'fe_name': 'vector1'})
    vector2: Vec3d = field(metadata={'fe_name': 'vector2'})
    radius1: float = field(metadata={'fe_name': 'radius1'})
    radius2: float = field(metadata={'fe_name': 'radius2'})
    fe_class: str = field(init=False, default='polar')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMat3dSphericalAngleMap(FEMat3dValuator):
    theta: float = field(metadata={'fe_name': 'theta'})
    phi: float = field(metadata={'fe_name': 'phi'})
    fe_class: str = field(init=False, default='angles')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMat3dSphericalMap(FEMat3dValuator):
    center: Vec3d = field(metadata={'fe_name': 'center'})
    vector: Vec3d = field(metadata={'fe_name': 'vector'})
    fe_class: str = field(init=False, default='spherical')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMat3dVectorMap(FEMat3dValuator):
    a: Vec3d = field(metadata={'fe_name': 'a'})
    d: Vec3d = field(metadata={'fe_name': 'd'})
    fe_class: str = field(init=False, default='vector')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEMathFunction(FEFunction1D):
    math: str = field(default='0', metadata={'fe_name': 'math', 'default': '0'})
    fe_class: str = field(init=False, default='math')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FEStepFunction(FEFunction1D):
    x0: float = field(metadata={'fe_name': 'x0'})
    left_val: float = field(metadata={'fe_name': 'left_val'})
    right_val: float = field(metadata={'fe_name': 'right_val'})
    fe_class: str = field(init=False, default='step')
    xml_tag: str = field(init=False, default='')
