# Auto-generated by codegen.generator
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from ..common.base import Annotated, FEBioEntity

from ..common.regions import SurfaceRef, coerce_surface

@dataclass(kw_only=True)
class FESurfaceConstraint(FEBioEntity):
    surface: Optional[SurfaceRef] = field(
        default=None, metadata={'fe_name': 'surface', 'is_property': True}
    )

    def __post_init__(self) -> None:
        if self.surface is not None:
            self.surface = coerce_surface(self.surface)

@dataclass(kw_only=True)
class FEPrescribedSurface(FESurfaceConstraint):
    pass


__all__ = [
    'FEPrescribedNormalDisplacement',
    'FESymmetryPlane',
    'SurfaceRef',
    'FESurfaceConstraint',
    'FEPrescribedSurface',
]

@dataclass(kw_only=True)
class FEPrescribedNormalDisplacement(FEPrescribedSurface):
    scale: float = field(metadata={'fe_name': 'scale'})
    surface_hint: int = field(metadata={'fe_name': 'surface_hint'})
    relative: bool = field(metadata={'fe_name': 'relative'})
    fe_class: str = field(init=False, default='normal displacement')
    xml_tag: str = field(init=False, default='constraint')

@dataclass(kw_only=True)
class FESymmetryPlane(FESurfaceConstraint):
    laugon: Any = field(metadata={'fe_name': 'laugon'})
    tol: Any = field(metadata={'fe_name': 'tol'})
    penalty: Any = field(metadata={'fe_name': 'penalty'})
    rhs: Any = field(metadata={'fe_name': 'rhs'})
    minaug: Any = field(metadata={'fe_name': 'minaug'})
    maxaug: Any = field(metadata={'fe_name': 'maxaug'})
    fe_class: str = field(init=False, default='symmetry plane')
    xml_tag: str = field(init=False, default='constraint')
