# Auto-generated by codegen.generator
from __future__ import annotations

from dataclasses import dataclass, field, fields
from typing import Any, Optional
import xml.etree.ElementTree as ET

def _indent(element: ET.Element, level: int = 0) -> None:
    '''Recursively indent an XML tree for pretty-printing.'''

    children = list(element)
    if children:
        if not element.text or not element.text.strip():
            element.text = '\n' + '  ' * (level + 1)
        for child in children:
            _indent(child, level + 1)
            if not child.tail or not child.tail.strip():
                child.tail = '\n' + '  ' * (level + 1)
        if not children[-1].tail or not children[-1].tail.strip():
            children[-1].tail = '\n' + '  ' * level
    elif level and (not element.tail or not element.tail.strip()):
        element.tail = '\n' + '  ' * level

class FEBioEntity:
    '''Base class for generated FEBio bindings.

    Attributes:
        fe_class: Name of the FEBio class represented by the binding.
        xml_tag: XML tag used for serialisation.
        xml_section: FEBio section that hosts the entity.
    '''

    fe_class: str = ''
    xml_tag: str = ''
    xml_section: str = ''

    def to_xml_element(self, name: str | None = None, *, tag_override: str | None = None) -> ET.Element:
        '''Serialise the entity into an XML element.

        Args:
            name: Optional name attribute for the FEBio element.

        Returns:
            Constructed XML element.
        '''

        tag = tag_override or self.xml_tag or 'bc'
        element = ET.Element(tag)
        element.set('type', self.fe_class)
        if name:
            element.set('name', name)
        for field_info in fields(self):
            if field_info.name in {'fe_class', 'xml_tag', 'xml_section'}:
                continue
            value = getattr(self, field_info.name)
            if value is None:
                continue
            metadata = field_info.metadata or {}
            param_name = metadata.get('fe_name', field_info.name)
            if metadata.get('is_property'):
                self._append_property_element(element, param_name, value)
                continue
            # Parameters are written as direct child tags instead of <param name="...">.
            param_element = ET.SubElement(element, param_name)
            param_element.text = str(value)
        return element

    def _append_property_element(self, parent: ET.Element, tag: str, value: Any) -> None:
        '''Append a property element handling FEBioEntity nesting.'''

        if isinstance(value, FEBioEntity):
            child = value.to_xml_element(tag_override=tag)
            parent.append(child)
            return
        if isinstance(value, (list, tuple)):
            for item in value:
                if item is None:
                    continue
                self._append_property_element(parent, tag, item)
            return
        prop_element = ET.SubElement(parent, tag)
        prop_element.text = str(value)

    def to_xml_string(self, name: str | None = None) -> str:
        '''Return the XML representation as a string.

        Args:
            name: Optional name attribute for the FEBio element.

        Returns:
            XML string representing the entity.
        '''

        element = self.to_xml_element(name=name)
        _indent(element)
        return ET.tostring(element, encoding='unicode')

from ..Core import Vec3d
from ..common.regions import (
    NodeSetRef,
    SurfaceRef,
    ElementSetRef,
    coerce_nodeset,
    coerce_surface,
    coerce_elementset,
)

class FEBoundaryCondition(FEBioEntity):
    pass

class FEContactInterface(FEBioEntity):
    pass

class FECoreClass(FEBioEntity):
    pass

class FEFixedBC(FEBioEntity):
    pass

class FEMat3dValuator(FEBioEntity):
    pass

class FEMat3dsValuator(FEBioEntity):
    pass

class FENodalBC(FEBioEntity):
    pass

class FEParamVec3(FEBioEntity):
    pass

class FEPrescribedNodeSet(FEBioEntity):
    pass

class FEPrescribedSurface(FEBioEntity):
    pass

class FESurfaceConstraint(FEBioEntity):
    pass

class mat3d(FEBioEntity):
    pass

class mat3ds(FEBioEntity):
    pass

class tens3drs(FEBioEntity):
    pass

class FEModelLoad(FEBioEntity):
    pass

@dataclass
class FENodalLoad(FEModelLoad):
    node_set: Optional[NodeSetRef] = field(
        default=None, metadata={'fe_name': 'node_set', 'is_property': True}
    )
    relative: Optional[bool] = field(default=None, metadata={'fe_name': 'relative'})

    def __post_init__(self) -> None:
        if self.node_set is not None:
            self.node_set = coerce_nodeset(self.node_set)

@dataclass
class FESurfaceLoad(FEModelLoad):
    surface: Optional[SurfaceRef] = field(
        default=None, metadata={'fe_name': 'surface', 'is_property': True}
    )
    relative: Optional[bool] = field(default=None, metadata={'fe_name': 'relative'})

    def __post_init__(self) -> None:
        if self.surface is not None:
            self.surface = coerce_surface(self.surface)

@dataclass
class FEBodyLoad(FEModelLoad):
    element_set: Optional[ElementSetRef] = field(
        default=None, metadata={'fe_name': 'domain', 'is_property': True}
    )
    relative: Optional[bool] = field(default=None, metadata={'fe_name': 'relative'})

    def __post_init__(self) -> None:
        if self.element_set is not None:
            self.element_set = coerce_elementset(self.element_set)

class FEBodyForce(FEBodyLoad):
    pass


__all__ = [
    'FEBearingLoad',
    'FECentrifugalBodyForce',
    'FEConstBodyForceOld',
    'FEGenericBodyForce',
    'FENodalForce',
    'FENonConstBodyForceOld',
    'FEPressureLoad',
    'FESurfaceForceUniform',
    'FETractionLoad',
    'Vec3d',
    'NodeSetRef',
    'SurfaceRef',
    'ElementSetRef',
    'FENodalLoad',
    'FESurfaceLoad',
    'FEBodyLoad',
    'FEBodyForce',
]

@dataclass
class FEBearingLoad(FESurfaceLoad):
    scale: Optional[float] = field(default=None, metadata={'fe_name': 'scale'})
    force: Optional[Vec3d] = field(default=None, metadata={'fe_name': 'force'})
    symmetric_stiffness: Optional[bool] = field(default=None, metadata={'fe_name': 'symmetric_stiffness'})
    linear: Optional[bool] = field(default=None, metadata={'fe_name': 'linear'})
    shell_bottom: Optional[bool] = field(default=None, metadata={'fe_name': 'shell_bottom'})
    profile: Optional[int] = field(default=None, metadata={'fe_name': 'profile'})
    fe_class: str = field(init=False, default='bearing load')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FECentrifugalBodyForce(FEBodyForce):
    angular_speed: Optional[float] = field(default=None, metadata={'fe_name': 'angular_speed', 'units': 'UNIT_ANGULAR_VELOCITY'})
    rotation_axis: Optional[Vec3d] = field(default=None, metadata={'fe_name': 'rotation_axis'})
    rotation_center: Optional[Vec3d] = field(default=None, metadata={'fe_name': 'rotation_center', 'units': 'UNIT_LENGTH'})
    fe_class: str = field(init=False, default='centrifugal')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FEConstBodyForceOld(FEBodyForce):
    x: Optional[Any] = field(default=None, metadata={'fe_name': 'x'})
    y: Optional[Any] = field(default=None, metadata={'fe_name': 'y'})
    z: Optional[Any] = field(default=None, metadata={'fe_name': 'z'})
    fe_class: str = field(init=False, default='const')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FEGenericBodyForce(FEBodyForce):
    force: Optional[FEParamVec3] = field(default=None, metadata={'fe_name': 'force', 'units': 'UNIT_SPECIFIC_FORCE'})
    fe_class: str = field(init=False, default='body force')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FENodalForce(FENodalLoad):
    value: Optional[FEParamVec3] = field(default=None, metadata={'fe_name': 'value', 'units': 'UNIT_FORCE'})
    shell_bottom: Optional[bool] = field(default=None, metadata={'fe_name': 'shell_bottom'})
    fe_class: str = field(init=False, default='nodal_force')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FENonConstBodyForceOld(FEBodyForce):
    x: Optional[Any] = field(default=None, metadata={'fe_name': 'x'})
    y: Optional[Any] = field(default=None, metadata={'fe_name': 'y'})
    z: Optional[Any] = field(default=None, metadata={'fe_name': 'z'})
    fe_class: str = field(init=False, default='non-const')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FEPressureLoad(FESurfaceLoad):
    pressure: Optional[float] = field(default=None, metadata={'fe_name': 'pressure', 'units': 'UNIT_PRESSURE'})
    symmetric_stiffness: Optional[bool] = field(default=None, metadata={'fe_name': 'symmetric_stiffness'})
    linear: Optional[bool] = field(default=None, metadata={'fe_name': 'linear'})
    shell_bottom: Optional[bool] = field(default=None, metadata={'fe_name': 'shell_bottom'})
    fe_class: str = field(init=False, default='pressure')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FESurfaceForceUniform(FESurfaceLoad):
    scale: Optional[float] = field(default=None, metadata={'fe_name': 'scale'})
    force: Optional[Vec3d] = field(default=None, metadata={'fe_name': 'force', 'units': 'UNIT_FORCE'})
    shell_bottom: Optional[bool] = field(default=None, metadata={'fe_name': 'shell_bottom'})
    fe_class: str = field(init=False, default='force')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')

@dataclass
class FETractionLoad(FESurfaceLoad):
    scale: Optional[float] = field(default=None, metadata={'fe_name': 'scale'})
    traction: Optional[FEParamVec3] = field(default=None, metadata={'fe_name': 'traction', 'units': 'UNIT_PRESSURE'})
    shell_bottom: Optional[bool] = field(default=None, metadata={'fe_name': 'shell_bottom'})
    linear: Optional[bool] = field(default=None, metadata={'fe_name': 'linear'})
    fe_class: str = field(init=False, default='traction')
    xml_tag: str = field(init=False, default='load')
    xml_section: str = field(init=False, default='Loads')
