# ---------------------------------------------------------------------------
# WARNING: This file was auto-generated by classExposer.generator.
# It is brittle by design—manual edits are likely to be lost on regeneration.
# Update the metadata or manifests instead, then re-run the generator.
# ---------------------------------------------------------------------------
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

from interFEBio.common.base import FEBioEntity
from interFEBio.common.regions import (
    ElementSetRef,
    NodeSetRef,
    SurfaceRef,
    coerce_elementset,
    coerce_nodeset,
    coerce_surface,
)
from interFEBio.Core.Parameters import FEParamVec3, Vec3d


class FEModelLoad(FEBioEntity):
    pass

@dataclass(kw_only=True)
class FENodalLoad(FEModelLoad):
    node_set: Optional[NodeSetRef] = field(
        default=None, metadata={'fe_name': 'node_set', 'is_property': True}
    )
    relative: Optional[bool] = field(default=None, metadata={'fe_name': 'relative'})

    def __post_init__(self) -> None:
        if self.node_set is not None:
            self.node_set = coerce_nodeset(self.node_set)

@dataclass(kw_only=True)
class FESurfaceLoad(FEModelLoad):
    surface: Optional[SurfaceRef] = field(
        default=None, metadata={'fe_name': 'surface', 'is_property': True}
    )
    relative: Optional[bool] = field(default=None, metadata={'fe_name': 'relative'})

    def __post_init__(self) -> None:
        if self.surface is not None:
            self.surface = coerce_surface(self.surface)

@dataclass(kw_only=True)
class FEBodyLoad(FEModelLoad):
    element_set: Optional[ElementSetRef] = field(
        default=None, metadata={'fe_name': 'domain', 'is_property': True}
    )
    relative: Optional[bool] = field(default=None, metadata={'fe_name': 'relative'})

    def __post_init__(self) -> None:
        if self.element_set is not None:
            self.element_set = coerce_elementset(self.element_set)

class FEBodyForce(FEBodyLoad):
    pass

__all__ = [
    'FEBearingLoad',
    'FECentrifugalBodyForce',
    'FEConstBodyForceOld',
    'FEGenericBodyForce',
    'FENodalForce',
    'FENonConstBodyForceOld',
    'FEPressureLoad',
    'FESurfaceForceUniform',
    'FETractionLoad',
]

@dataclass(kw_only=True)
class FEBearingLoad(FESurfaceLoad):
    scale: float = field(metadata={'fe_name': 'scale'})
    force: Vec3d = field(metadata={'fe_name': 'force'})
    symmetric_stiffness: bool = field(metadata={'fe_name': 'symmetric_stiffness'})
    linear: bool = field(metadata={'fe_name': 'linear'})
    shell_bottom: bool = field(metadata={'fe_name': 'shell_bottom'})
    profile: int = field(metadata={'fe_name': 'profile'})
    fe_class: str = field(init=False, default='bearing load')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FECentrifugalBodyForce(FEBodyForce):
    angular_speed: float = field(metadata={'fe_name': 'angular_speed', 'units': 'UNIT_ANGULAR_VELOCITY'})
    rotation_axis: Vec3d = field(metadata={'fe_name': 'rotation_axis'})
    rotation_center: Vec3d = field(metadata={'fe_name': 'rotation_center', 'units': 'UNIT_LENGTH'})
    fe_class: str = field(init=False, default='centrifugal')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FEConstBodyForceOld(FEBodyForce):
    x: Any = field(metadata={'fe_name': 'x'})
    y: Any = field(metadata={'fe_name': 'y'})
    z: Any = field(metadata={'fe_name': 'z'})
    fe_class: str = field(init=False, default='const')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FEGenericBodyForce(FEBodyForce):
    force: FEParamVec3 = field(metadata={'fe_name': 'force', 'units': 'UNIT_SPECIFIC_FORCE'})
    fe_class: str = field(init=False, default='body force')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FENodalForce(FENodalLoad):
    value: FEParamVec3 = field(metadata={'fe_name': 'value', 'units': 'UNIT_FORCE'})
    shell_bottom: bool = field(metadata={'fe_name': 'shell_bottom'})
    fe_class: str = field(init=False, default='nodal_force')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FENonConstBodyForceOld(FEBodyForce):
    x: Any = field(metadata={'fe_name': 'x'})
    y: Any = field(metadata={'fe_name': 'y'})
    z: Any = field(metadata={'fe_name': 'z'})
    fe_class: str = field(init=False, default='non-const')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FEPressureLoad(FESurfaceLoad):
    pressure: float = field(metadata={'fe_name': 'pressure', 'units': 'UNIT_PRESSURE'})
    symmetric_stiffness: bool = field(metadata={'fe_name': 'symmetric_stiffness'})
    linear: bool = field(metadata={'fe_name': 'linear'})
    shell_bottom: bool = field(metadata={'fe_name': 'shell_bottom'})
    fe_class: str = field(init=False, default='pressure')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FESurfaceForceUniform(FESurfaceLoad):
    scale: float = field(metadata={'fe_name': 'scale'})
    force: Vec3d = field(metadata={'fe_name': 'force', 'units': 'UNIT_FORCE'})
    shell_bottom: bool = field(metadata={'fe_name': 'shell_bottom'})
    fe_class: str = field(init=False, default='force')
    xml_tag: str = field(init=False, default='load')

@dataclass(kw_only=True)
class FETractionLoad(FESurfaceLoad):
    scale: float = field(metadata={'fe_name': 'scale'})
    traction: FEParamVec3 = field(metadata={'fe_name': 'traction', 'units': 'UNIT_PRESSURE'})
    shell_bottom: bool = field(metadata={'fe_name': 'shell_bottom'})
    linear: bool = field(metadata={'fe_name': 'linear'})
    fe_class: str = field(init=False, default='traction')
    xml_tag: str = field(init=False, default='load')
