# ---------------------------------------------------------------------------
# WARNING: This file was auto-generated by classExposer.generator.
# It is brittle by design—manual edits are likely to be lost on regeneration.
# Update the metadata or manifests instead, then re-run the generator.
# ---------------------------------------------------------------------------
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from interFEBio.common.base import Annotated, FEBioEntity, RangeSpec


class FECoreBase(FEBioEntity):
    pass

class FENewtonStrategy(FEBioEntity):
    pass

class LinearSolver(FEBioEntity):
    pass

__all__ = [
    'BFGSSolver',
    'FESolver',
    'PardisoSolver',
    'FENewtonSolver',
    'FESolidSolver2',
]

@dataclass(kw_only=True)
class BFGSSolver(FENewtonStrategy):
    max_ups: int = field(metadata={'fe_name': 'max_ups'})
    max_buffer_size: Annotated[int, 'RangeSpec(min=0, min_inclusive=True)'] = field(metadata={'fe_name': 'max_buffer_size', 'range': {'min': 0, 'min_inclusive': True}})
    cycle_buffer: bool = field(metadata={'fe_name': 'cycle_buffer'})
    cmax: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'cmax', 'range': {'min': 0.0, 'min_inclusive': True}})
    fe_class: str = field(init=False, default='BFGS')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FESolver(FECoreBase):
    class SymmetricStiffness(Enum):
        NON_SYMMETRIC = 0
        SYMMETRIC = 1
        SYMMETRIC_STRUCTURE = 2
        PREFERRED = 3

    class EquationScheme(Enum):
        STAGGERED = 0
        BLOCK = 1

    class EquationOrder(Enum):
        DEFAULT = 0
        REVERSE = 1
        FEBIO2 = 2

    symmetric_stiffness: SymmetricStiffness | int = field(default='REAL_SYMMETRIC', metadata={'fe_name': 'symmetric_stiffness', 'enum': ['non-symmetric', 'symmetric', 'symmetric structure', 'preferred'], 'long_name': 'matrix format', 'enum_class': 'SymmetricStiffness', 'default': 'REAL_SYMMETRIC'})
    equation_scheme: EquationScheme | int = field(default=EquationScheme.STAGGERED, metadata={'fe_name': 'equation_scheme', 'enum': ['staggered', 'block'], 'enum_class': 'EquationScheme', 'default': 0})
    equation_order: EquationOrder | int = field(default='EQUATION_ORDER::NORMAL_ORDER', metadata={'fe_name': 'equation_order', 'enum': ['default', 'reverse', 'febio2'], 'enum_class': 'EquationOrder', 'default': 'EQUATION_ORDER::NORMAL_ORDER'})
    optimize_bw: bool = field(default=False, metadata={'fe_name': 'optimize_bw', 'default': False})
    fe_class: str = field(init=False, default='FESolver')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class PardisoSolver(LinearSolver):
    print_condition_number: bool = field(default=False, metadata={'fe_name': 'print_condition_number', 'default': False})
    precondition: bool = field(default=False, metadata={'fe_name': 'precondition', 'default': False})
    msglvl: int = field(default=0, metadata={'fe_name': 'msglvl', 'default': 0})
    fe_class: str = field(init=False, default='pardiso')
    xml_tag: str = field(init=False, default='material')

@dataclass(kw_only=True)
class FENewtonSolver(FESolver):
    lstol: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0.9, metadata={'fe_name': 'lstol', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0.9})
    lsmin: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0.01, metadata={'fe_name': 'lsmin', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0.01})
    lsiter: Annotated[int, 'RangeSpec(min=0, min_inclusive=True)'] = field(default=5, metadata={'fe_name': 'lsiter', 'range': {'min': 0, 'min_inclusive': True}, 'default': 5})
    ls_check_jacobians: bool = field(default=False, metadata={'fe_name': 'ls_check_jacobians', 'default': False})
    max_refs: Annotated[int, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=15, metadata={'fe_name': 'max_refs', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 15})
    check_zero_diagonal: bool = field(default=False, metadata={'fe_name': 'check_zero_diagonal', 'default': False})
    zero_diagonal_tol: float = field(default=0.0, metadata={'fe_name': 'zero_diagonal_tol', 'default': 0.0})
    force_partition: int = field(default=0, metadata={'fe_name': 'force_partition', 'default': 0})
    reform_each_time_step: bool = field(default=True, metadata={'fe_name': 'reform_each_time_step', 'default': True})
    reform_augment: bool = field(default=False, metadata={'fe_name': 'reform_augment', 'default': False})
    diverge_reform: bool = field(default=True, metadata={'fe_name': 'diverge_reform', 'default': True})
    min_residual: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=1e-20, metadata={'fe_name': 'min_residual', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 1e-20})
    max_residual: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0, metadata={'fe_name': 'max_residual', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0})
    qn_method: Optional[FENewtonStrategy] = field(default=None, metadata={'fe_name': 'qn_method', 'is_property': True, 'optional': True})
    linear_solver: Optional[LinearSolver] = field(default=None, metadata={'fe_name': 'linear_solver', 'is_property': True, 'optional': True})
    fe_class: str = field(init=False, default='FENewtonSolver')
    xml_tag: str = field(init=False, default='')

@dataclass(kw_only=True)
class FESolidSolver2(FENewtonSolver):
    class ArcLength(Enum):
        NONE = 0
        CRISFIELD = 1

    dtol: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0.001, metadata={'fe_name': 'dtol', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0.001})
    etol: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0.01, metadata={'fe_name': 'etol', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0.01})
    rtol: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0, metadata={'fe_name': 'rtol', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0})
    rhoi: float = field(default=-2, metadata={'fe_name': 'rhoi', 'default': -2})
    alpha: float = field(default=1.0, metadata={'fe_name': 'alpha', 'default': 1.0})
    beta: float = field(default=0.25, metadata={'fe_name': 'beta', 'default': 0.25})
    gamma: float = field(default=0.5, metadata={'fe_name': 'gamma', 'default': 0.5})
    logsolve: bool = field(default=False, metadata={'fe_name': 'logSolve', 'default': False})
    arc_length: ArcLength | int = field(default=ArcLength.NONE, metadata={'fe_name': 'arc_length', 'enum': ['NONE', 'CRISFIELD'], 'enum_class': 'ArcLength', 'default': 0})
    arc_length_scale: float = field(default=0.0, metadata={'fe_name': 'arc_length_scale', 'default': 0.0})
    fe_class: str = field(init=False, default='solid')
    xml_tag: str = field(init=False, default='')
