# ---------------------------------------------------------------------------
# WARNING: This file was auto-generated by classExposer.generator.
# It is brittle by design—manual edits are likely to be lost on regeneration.
# Update the metadata or manifests instead, then re-run the generator.
# ---------------------------------------------------------------------------
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from ..common.base import FEBioEntity
from ..common.regions import NodeSetRef, SurfaceRef, coerce_nodeset, coerce_surface
from ..Core import Vec3d, mat3d


class FEBoundaryCondition(FEBioEntity):
    pass

class FECoreClass(FEBioEntity):
    pass

@dataclass(kw_only=True)
class FENodalBC(FEBoundaryCondition):
    node_set: Optional[NodeSetRef] = field(
        default=None, metadata={'fe_name': 'node_set', 'is_property': True}
    )

    def __post_init__(self) -> None:
        if self.node_set is not None:
            self.node_set = coerce_nodeset(self.node_set)

class FEFixedBC(FENodalBC):
    pass

class FEPrescribedNodeSet(FENodalBC):
    pass

@dataclass(kw_only=True)
class FEPrescribedSurface(FEBoundaryCondition):
    surface: Optional[SurfaceRef] = field(
        default=None, metadata={'fe_name': 'surface', 'is_property': True}
    )

    def __post_init__(self) -> None:
        if self.surface is not None:
            self.surface = coerce_surface(self.surface)

__all__ = [
    'FEBCPrescribedDeformation',
    'FEBCRigidDeformation',
    'FEFixedDisplacement',
    'FEFixedRotation',
    'FEFixedShellDisplacement',
    'FELinearConstraint',
    'FELinearConstraintDOF',
    'FEPrescribedDisplacement',
    'FEPrescribedNormalDisplacement',
    'FEPrescribedRotation',
    'FEPrescribedShellDisplacement',
    'FERigidNodeSet',
]

@dataclass(kw_only=True)
class FEBCPrescribedDeformation(FEPrescribedNodeSet):
    scale: float = field(metadata={'fe_name': 'scale'})
    f: mat3d = field(metadata={'fe_name': 'F'})
    fe_class: str = field(init=False, default='prescribed deformation')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEBCRigidDeformation(FEPrescribedNodeSet):
    pos: Vec3d = field(metadata={'fe_name': 'pos'})
    rot: Vec3d = field(metadata={'fe_name': 'rot'})
    fe_class: str = field(init=False, default='rigid deformation')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEFixedDisplacement(FEFixedBC):
    x_dof: bool = field(metadata={'fe_name': 'x_dof', 'long_name': 'x-displacement'})
    y_dof: bool = field(metadata={'fe_name': 'y_dof', 'long_name': 'y-displacement'})
    z_dof: bool = field(metadata={'fe_name': 'z_dof', 'long_name': 'z-displacement'})
    fe_class: str = field(init=False, default='zero displacement')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEFixedRotation(FEFixedBC):
    u_dof: Any = field(metadata={'fe_name': 'u_dof', 'long_name': 'x-rotation'})
    v_dof: Any = field(metadata={'fe_name': 'v_dof', 'long_name': 'y-rotation'})
    w_dof: Any = field(metadata={'fe_name': 'w_dof', 'long_name': 'z-rotation'})
    fe_class: str = field(init=False, default='zero rotation')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEFixedShellDisplacement(FEFixedBC):
    sx_dof: bool = field(metadata={'fe_name': 'sx_dof', 'long_name': 'sx-displacement'})
    sy_dof: bool = field(metadata={'fe_name': 'sy_dof', 'long_name': 'sy-displacement'})
    sz_dof: bool = field(metadata={'fe_name': 'sz_dof', 'long_name': 'sz-displacement'})
    fe_class: str = field(init=False, default='zero shell displacement')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FELinearConstraint(FEBoundaryCondition):
    child_dof: int = field(metadata={'fe_name': 'child_dof', 'is_property': True})
    offset: float = field(default=0.0, metadata={'fe_name': 'offset', 'default': 0.0})
    fe_class: str = field(init=False, default='linear constraint')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FELinearConstraintDOF(FECoreClass):
    dof: int = field(metadata={'fe_name': 'dof', 'range': '$(dof_list)', 'enum': '$(dof_list)'})
    node: int = field(metadata={'fe_name': 'node'})
    value: float = field(metadata={'fe_name': 'value'})
    fe_class: str = field(init=False, default='child_dof')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEPrescribedDisplacement(FENodalBC):
    class Dof(Enum):
        X = 0
        Y = 1
        Z = 2

    value: float = field(metadata={'fe_name': 'value', 'units': 'UNIT_LENGTH'})
    relative: bool = field(metadata={'fe_name': 'relative'})
    dof: Dof | int = field(default=Dof.X, metadata={'fe_name': 'dof', 'range': '$(dof_list:displacement)', 'enum': ['x', 'y', 'z'], 'enum_class': 'Dof', 'default': 0})
    fe_class: str = field(init=False, default='prescribed displacement')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEPrescribedNormalDisplacement(FEPrescribedSurface):
    scale: float = field(metadata={'fe_name': 'scale'})
    surface_hint: int = field(metadata={'fe_name': 'surface_hint'})
    relative: bool = field(metadata={'fe_name': 'relative'})
    fe_class: str = field(init=False, default='normal displacement')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEPrescribedRotation(FEBoundaryCondition):
    dof: int = field(metadata={'fe_name': 'dof', 'range': '$(dof_list:rotation)', 'enum': '$(dof_list:rotation)'})
    value: float = field(metadata={'fe_name': 'value', 'units': 'UNIT_RADIAN'})
    relative: bool = field(metadata={'fe_name': 'relative'})
    fe_class: str = field(init=False, default='prescribed rotation')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FEPrescribedShellDisplacement(FENodalBC):
    dof: int = field(metadata={'fe_name': 'dof', 'range': '$(dof_list:shell displacement)', 'enum': '$(dof_list:shell displacement)'})
    value: float = field(metadata={'fe_name': 'value', 'units': 'UNIT_LENGTH'})
    relative: bool = field(metadata={'fe_name': 'relative'})
    fe_class: str = field(init=False, default='prescribed shell displacement')
    xml_tag: str = field(init=False, default='bc')

@dataclass(kw_only=True)
class FERigidNodeSet(FENodalBC):
    rb: int = field(default=-1, metadata={'fe_name': 'rb', 'default': -1})
    clamp_shells: bool = field(default=True, metadata={'fe_name': 'clamp_shells', 'default': True})
    fe_class: str = field(init=False, default='rigid')
    xml_tag: str = field(init=False, default='bc')
