# ---------------------------------------------------------------------------
# WARNING: This file was auto-generated by classExposer.generator.
# It is brittle by design—manual edits are likely to be lost on regeneration.
# Update the metadata or manifests instead, then re-run the generator.
# ---------------------------------------------------------------------------
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from interFEBio.common.base import FEBioEntity
from interFEBio.common.regions import SurfaceRef, coerce_surface


@dataclass(kw_only=True)
class FEContactInterface(FEBioEntity):
    primary: Optional[SurfaceRef] = field(
        default=None, metadata={'fe_name': 'primary', 'is_property': True}
    )
    secondary: Optional[SurfaceRef] = field(
        default=None, metadata={'fe_name': 'secondary', 'is_property': True}
    )

    def __post_init__(self) -> None:
        if self.primary is not None:
            self.primary = coerce_surface(self.primary)
        if self.secondary is not None:
            self.secondary = coerce_surface(self.secondary)

__all__ = [
    'FESlidingElasticInterface',
]

@dataclass(kw_only=True)
class FESlidingElasticInterface(FEContactInterface):
    class Laugon(Enum):
        PENALTY = 0
        AUGLAG = 1

    laugon: Laugon | int = field(default=Laugon.PENALTY, metadata={'fe_name': 'laugon', 'enum': ['PENALTY', 'AUGLAG'], 'long_name': 'Enforcement method', 'enum_class': 'Laugon', 'default': 0})
    tolerance: float = field(default=0.1, metadata={'fe_name': 'tolerance', 'default': 0.1})
    gaptol: float = field(default=0, metadata={'fe_name': 'gaptol', 'units': 'UNIT_LENGTH', 'default': 0})
    penalty: float = field(default=1, metadata={'fe_name': 'penalty', 'default': 1})
    auto_penalty: bool = field(default=False, metadata={'fe_name': 'auto_penalty', 'default': False})
    update_penalty: bool = field(default=False, metadata={'fe_name': 'update_penalty', 'default': False})
    two_pass: bool = field(default=False, metadata={'fe_name': 'two_pass', 'default': False})
    knmult: int = field(default=0, metadata={'fe_name': 'knmult', 'default': 0})
    search_tol: float = field(default=0.01, metadata={'fe_name': 'search_tol', 'default': 0.01})
    symmetric_stiffness: bool = field(default=True, metadata={'fe_name': 'symmetric_stiffness', 'default': True})
    search_radius: float = field(default=1.0, metadata={'fe_name': 'search_radius', 'units': 'UNIT_LENGTH', 'default': 1.0})
    seg_up: int = field(default=0, metadata={'fe_name': 'seg_up', 'default': 0})
    tension: bool = field(default=False, metadata={'fe_name': 'tension', 'default': False})
    minaug: int = field(default=0, metadata={'fe_name': 'minaug', 'default': 0})
    maxaug: int = field(default=10, metadata={'fe_name': 'maxaug', 'default': 10})
    node_reloc: bool = field(default=False, metadata={'fe_name': 'node_reloc', 'default': False})
    fric_coeff: float = field(default=0.0, metadata={'fe_name': 'fric_coeff', 'default': 0.0})
    smooth_aug: bool = field(default=False, metadata={'fe_name': 'smooth_aug', 'default': False})
    flip_primary: bool = field(default=False, metadata={'fe_name': 'flip_primary', 'default': False})
    flip_secondary: bool = field(default=False, metadata={'fe_name': 'flip_secondary', 'default': False})
    shell_bottom_primary: bool = field(default=False, metadata={'fe_name': 'shell_bottom_primary', 'default': False})
    shell_bottom_secondary: bool = field(default=False, metadata={'fe_name': 'shell_bottom_secondary', 'default': False})
    offset: float = field(default=0, metadata={'fe_name': 'offset', 'units': 'UNIT_LENGTH', 'default': 0})
    fe_class: str = field(init=False, default='sliding-elastic')
    xml_tag: str = field(init=False, default='material')
