# ---------------------------------------------------------------------------
# WARNING: This file was auto-generated by classExposer.generator.
# It is brittle by design—manual edits are likely to be lost on regeneration.
# Update the metadata or manifests instead, then re-run the generator.
# ---------------------------------------------------------------------------
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from interFEBio.common.base import Annotated, FEBioEntity, RangeSpec


class FECoreBase(FEBioEntity):
    pass

class FENewtonStrategy(FEBioEntity):
    pass

class FEParamContainer(FEBioEntity):
    pass

class FESolver(FEBioEntity):
    pass

class LinearSolver(FEBioEntity):
    pass

__all__ = [
    'BFGSSolver',
    'FEAnalysis',
    'FEBroydenStrategy',
    'FENewtonSolver',
    'FESolidSolver2',
    'FETimeStepController',
    'PardisoSolver',
]

@dataclass(kw_only=True)
class BFGSSolver(FENewtonStrategy):
    max_ups: int = field(metadata={'fe_name': 'max_ups'})
    max_buffer_size: Annotated[int, 'RangeSpec(min=0, min_inclusive=True)'] = field(metadata={'fe_name': 'max_buffer_size', 'range': {'min': 0, 'min_inclusive': True}})
    cycle_buffer: bool = field(metadata={'fe_name': 'cycle_buffer'})
    cmax: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'cmax', 'range': {'min': 0.0, 'min_inclusive': True}})
    fe_class: str = field(init=False, default='BFGS')
    xml_tag: str = field(init=False, default='material')

@dataclass(kw_only=True)
class FEAnalysis(FECoreBase):
    class PlotLevel(Enum):
        PLOT_NEVER = 0
        PLOT_MAJOR_ITRS = 1
        PLOT_MINOR_ITRS = 2
        PLOT_MUST_POINTS = 3
        PLOT_FINAL = 4
        PLOT_AUGMENTATIONS = 5
        PLOT_STEP_FINAL = 6

    class OutputLevel(Enum):
        OUTPUT_NEVER = 0
        OUTPUT_MAJOR_ITRS = 1
        OUTPUT_MINOR_ITRS = 2
        OUTPUT_MUST_POINTS = 3
        OUTPUT_FINAL = 4

    analysis: int = field(default=0, metadata={'fe_name': 'analysis', 'default': 0})
    time_steps: Annotated[int, 'RangeSpec(min=-1, min_inclusive=True)'] = field(default=10, metadata={'fe_name': 'time_steps', 'range': {'min': -1, 'min_inclusive': True}, 'default': 10})
    step_size: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0.1, metadata={'fe_name': 'step_size', 'units': 'UNIT_TIME', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0.1})
    final_time: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(default=0.0, metadata={'fe_name': 'final_time', 'range': {'min': 0.0, 'min_inclusive': True}, 'default': 0.0})
    plot_zero_state: bool = field(default=False, metadata={'fe_name': 'plot_zero_state', 'default': False})
    plot_range: tuple[int, int] = field(default=(0, -1), metadata={'fe_name': 'plot_range', 'default': [0, -1]})
    plot_level: PlotLevel | int = field(default=PlotLevel.PLOT_MAJOR_ITRS, metadata={'fe_name': 'plot_level', 'enum': ['PLOT_NEVER', 'PLOT_MAJOR_ITRS', 'PLOT_MINOR_ITRS', 'PLOT_MUST_POINTS', 'PLOT_FINAL', 'PLOT_AUGMENTATIONS', 'PLOT_STEP_FINAL'], 'enum_class': 'PlotLevel', 'default': 1})
    output_level: OutputLevel | int = field(default=OutputLevel.OUTPUT_MAJOR_ITRS, metadata={'fe_name': 'output_level', 'enum': ['OUTPUT_NEVER', 'OUTPUT_MAJOR_ITRS', 'OUTPUT_MINOR_ITRS', 'OUTPUT_MUST_POINTS', 'OUTPUT_FINAL'], 'enum_class': 'OutputLevel', 'default': 1})
    plot_stride: int = field(default=1, metadata={'fe_name': 'plot_stride', 'default': 1})
    output_stride: int = field(default=1, metadata={'fe_name': 'output_stride', 'default': 1})
    adaptor_re_solve: bool = field(default=True, metadata={'fe_name': 'adaptor_re_solve', 'long_name': 're-solve after adaptation', 'default': True})
    time_stepper: Optional[FETimeStepController] = field(default=None, metadata={'fe_name': 'time_stepper', 'is_property': True, 'optional': True})
    fe_class: str = field(init=False, default='analysis')
    xml_tag: str = field(init=False, default='material')

@dataclass(kw_only=True)
class FEBroydenStrategy(FENewtonStrategy):
    max_ups: int = field(metadata={'fe_name': 'max_ups'})
    max_buffer_size: Annotated[int, 'RangeSpec(min=0, min_inclusive=True)'] = field(metadata={'fe_name': 'max_buffer_size', 'range': {'min': 0, 'min_inclusive': True}})
    cycle_buffer: bool = field(metadata={'fe_name': 'cycle_buffer'})
    cmax: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'cmax', 'range': {'min': 0.0, 'min_inclusive': True}})
    fe_class: str = field(init=False, default='Broyden')
    xml_tag: str = field(init=False, default='material')

@dataclass(kw_only=True)
class FENewtonSolver(FESolver):
    max_refs: Annotated[int, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'max_refs', 'range': {'min': 0.0, 'min_inclusive': True}})
    check_zero_diagonal: bool = field(metadata={'fe_name': 'check_zero_diagonal'})
    zero_diagonal_tol: float = field(metadata={'fe_name': 'zero_diagonal_tol'})
    force_partition: int = field(metadata={'fe_name': 'force_partition'})
    reform_each_time_step: bool = field(metadata={'fe_name': 'reform_each_time_step'})
    reform_augment: bool = field(metadata={'fe_name': 'reform_augment'})
    diverge_reform: bool = field(metadata={'fe_name': 'diverge_reform'})
    min_residual: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'min_residual', 'range': {'min': 0.0, 'min_inclusive': True}})
    max_residual: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'max_residual', 'range': {'min': 0.0, 'min_inclusive': True}})
    qn_method: Optional[FENewtonStrategy] = field(default=None, metadata={'fe_name': 'qn_method', 'is_property': True, 'optional': True})
    linear_solver: Optional[LinearSolver] = field(default=None, metadata={'fe_name': 'linear_solver', 'is_property': True, 'optional': True})
    fe_class: str = field(init=False, default='FENewtonSolver')
    xml_tag: str = field(init=False, default='material')

@dataclass(kw_only=True)
class FESolidSolver2(FENewtonSolver):
    dtol: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'dtol', 'range': {'min': 0.0, 'min_inclusive': True}})
    etol: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'etol', 'range': {'min': 0.0, 'min_inclusive': True}})
    rtol: Annotated[float, 'RangeSpec(min=0.0, min_inclusive=True)'] = field(metadata={'fe_name': 'rtol', 'range': {'min': 0.0, 'min_inclusive': True}})
    rhoi: float = field(metadata={'fe_name': 'rhoi'})
    alpha: float = field(metadata={'fe_name': 'alpha'})
    beta: float = field(metadata={'fe_name': 'beta'})
    gamma: float = field(metadata={'fe_name': 'gamma'})
    logsolve: bool = field(metadata={'fe_name': 'logSolve'})
    arc_length: int = field(metadata={'fe_name': 'arc_length'})
    arc_length_scale: float = field(metadata={'fe_name': 'arc_length_scale'})
    init_accelerations: bool = field(metadata={'fe_name': 'init_accelerations'})
    fe_class: str = field(init=False, default='solid')
    xml_tag: str = field(init=False, default='material')

@dataclass(kw_only=True)
class FETimeStepController(FEParamContainer):
    max_retries: int = field(metadata={'fe_name': 'max_retries', 'long_name': 'max retries'})
    opt_iter: int = field(metadata={'fe_name': 'opt_iter', 'long_name': 'optimal iterations'})
    dtmin: float = field(metadata={'fe_name': 'dtmin', 'long_name': 'min stepsize'})
    dtmax: float = field(metadata={'fe_name': 'dtmax', 'long_name': 'max stepsize'})
    aggressiveness: int = field(metadata={'fe_name': 'aggressiveness'})
    cutback: float = field(metadata={'fe_name': 'cutback'})
    dtforce: bool = field(metadata={'fe_name': 'dtforce'})
    fe_class: str = field(init=False, default='default')
    xml_tag: str = field(init=False, default='material')

@dataclass(kw_only=True)
class PardisoSolver(LinearSolver):
    print_condition_number: bool = field(metadata={'fe_name': 'print_condition_number'})
    precondition: bool = field(metadata={'fe_name': 'precondition'})
    msglvl: int = field(metadata={'fe_name': 'msglvl'})
    fe_class: str = field(init=False, default='pardiso')
    xml_tag: str = field(init=False, default='material')
